  create table address (
        id bigint generated by default as identity (start with 1),
        city varchar(255),
        postal_code varchar(255),
        street varchar(255),
        street_number varchar(255),
        primary key (id)
    );

    create table author (
        publications integer,
        author_id bigint not null,
        primary key (author_id)
    );

    create table book (
        id bigint generated by default as identity (start with 1),
        title varchar(50) not null,
        library_id bigint,
        primary key (id)
    );

    create table book_author (
        book_id bigint not null,
        author_id bigint not null,
        primary key (book_id, author_id)
    );

    create table library (
        id bigint generated by default as identity (start with 1),
        name varchar(255),
        address_id bigint,
        primary key (id)
    );

    create table person (
        id bigint generated by default as identity (start with 1),
        age integer not null,
        first_name varchar(50) not null,
        last_name varchar(50) not null,
        primary key (id)
    );

    alter table author
        add constraint FK_igkj4jv2ti0g2k5t99u5m68bl
        foreign key (author_id)
        references person;

    alter table book
        add constraint FK_3pkewppfc8dyahqow87upbemb
        foreign key (library_id)
        references library;

    alter table book_author
        add constraint FK_6cmg2roopa9a4c97uxetgf2e9
        foreign key (author_id)
        references author;

    alter table book_author
        add constraint FK_q37qkj7serxg0bh56m450uigs
        foreign key (book_id)
        references book;

    alter table library
        add constraint FK_44cxndexsnwyp4poo41jmhwvg
        foreign key (address_id)
        references address;